#!/usr/bin/env ruby

git_bundles = [
    "git://github.com/scrooloose/nerdtree.git",
    "git://github.com/tpope/vim-fugitive.git",
    "git://github.com/tpope/vim-markdown.git",
    "git://github.com/tpope/vim-surround.git",
    "git://github.com/vim-ruby/vim-ruby.git",
    "git://github.com/t9md/vim-chef.git",
    "git://github.com/dougireton/vim-chef.git",
    "git://github.com/bling/vim-airline.git",
    "git://github.com/taq/vim-git-branch-info",
    "git://github.com/SirVer/ultisnips.git",
    "git://github.com/tomtom/tcomment_vim.git",
    "git://github.com/tpope/vim-endwise.git",
    "git://github.com/scrooloose/syntastic.git",
    "git://github.com/tpope/vim-sensible.git",
    "git://github.com/kien/rainbow_parentheses.vim.git",
    "git://github.com/szw/vim-ctrlspace.git",
    "git://github.com/sickill/vim-monokai",
    "git://github.com/myusuf3/numbers.vim.git",
    "git://github.com/ervandew/supertab",
    "git://github.com/airblade/vim-gitgutter.git"
]

vim_org_scripts = [
    ["IndexedSearch", "7062",  "plugin"]
    # ["closetag", "13", "scripts"]
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.mkdir_p(bundles_dir)
FileUtils.cd(bundles_dir)

puts "trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
    dir = url.split('/').last.sub(/\.git$/, '')
    if url == "git://github.com/dougireton/vim-chef.git"
        dir = "vim-chef-ft"
    end
    puts "unpacking #{url} into #{dir}"
    `git clone #{url} #{dir}`
    FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
    puts "downloading #{name}"
    local_file = File.join(name, script_type, "#{name}.vim")
    FileUtils.mkdir_p(File.dirname(local_file))
    File.open(local_file, "w") do |file|
        file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
    end
end
